Import the numpy module

In [1]:
import numpy as np

Create a 1d numpy array called arr1 that looks like the one below. Display it.

In [2]:
arr1 = np.array([3, 6, 9, 12, 15])

In [3]:
print(f"array({arr1})")

array([ 3  6  9 12 15])


Print out the 3rd element of the array.

In [4]:
third_element = arr1[2]
print(third_element)

9


Create a 2d numpy array called arr2 that looks like the one below. Display it.

In [5]:
arr2 = np.array([[2, 4, 6], [3, 6, 9], [4, 8, 12]])

In [6]:
print(f"array({arr2})")

array([[ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]])


Print out the element at row=3,col=2.

In [7]:
element_at_3_2 = arr2[2, 1]
print(element_at_3_2)

8


Create an array that goes from 0 to 100 with step=3. Display it.

In [8]:
arr3 = np.arange(0, 101, step=3)

In [9]:
print(f"array({arr3})")

array([ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99])


Create a 10x5 2d array filled with zeroes. Display it.

In [10]:
zero_array = np.zeros((10, 5))

In [11]:
print(f"array({zero_array})")

array([[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]])


Create an array called lin1d, that has 100 data points spaced between 57 and 108. Display it.

In [12]:
lin1d = np.linspace(57, 108, 100)

In [13]:
print(f"array({lin1d})")

array([ 57.          57.51515152  58.03030303  58.54545455  59.06060606
  59.57575758  60.09090909  60.60606061  61.12121212  61.63636364
  62.15151515  62.66666667  63.18181818  63.6969697   64.21212121
  64.72727273  65.24242424  65.75757576  66.27272727  66.78787879
  67.3030303   67.81818182  68.33333333  68.84848485  69.36363636
  69.87878788  70.39393939  70.90909091  71.42424242  71.93939394
  72.45454545  72.96969697  73.48484848  74.          74.51515152
  75.03030303  75.54545455  76.06060606  76.57575758  77.09090909
  77.60606061  78.12121212  78.63636364  79.15151515  79.66666667
  80.18181818  80.6969697   81.21212121  81.72727273  82.24242424
  82.75757576  83.27272727  83.78787879  84.3030303   84.81818182
  85.33333333  85.84848485  86.36363636  86.87878788  87.39393939
  87.90909091  88.42424242  88.93939394  89.45454545  89.96969697
  90.48484848  91.          91.51515152  92.03030303  92.54545455
  93.06060606  93.57575758  94.09090909  94.60606061  95.12121212
  95

Reshape lin1d to be 10x10 and call it lin2d. Display it.

In [14]:
lin2d = np.reshape(lin1d, (10, 10))

In [15]:
print(f"array({lin2d})")

array([[ 57.          57.51515152  58.03030303  58.54545455  59.06060606
   59.57575758  60.09090909  60.60606061  61.12121212  61.63636364]
 [ 62.15151515  62.66666667  63.18181818  63.6969697   64.21212121
   64.72727273  65.24242424  65.75757576  66.27272727  66.78787879]
 [ 67.3030303   67.81818182  68.33333333  68.84848485  69.36363636
   69.87878788  70.39393939  70.90909091  71.42424242  71.93939394]
 [ 72.45454545  72.96969697  73.48484848  74.          74.51515152
   75.03030303  75.54545455  76.06060606  76.57575758  77.09090909]
 [ 77.60606061  78.12121212  78.63636364  79.15151515  79.66666667
   80.18181818  80.6969697   81.21212121  81.72727273  82.24242424]
 [ 82.75757576  83.27272727  83.78787879  84.3030303   84.81818182
   85.33333333  85.84848485  86.36363636  86.87878788  87.39393939]
 [ 87.90909091  88.42424242  88.93939394  89.45454545  89.96969697
   90.48484848  91.          91.51515152  92.03030303  92.54545455]
 [ 93.06060606  93.57575758  94.09090909  94.6060

Print out the shape of lin1d and lin2d.

In [16]:
print(f"lin1d: {lin1d.shape}")
print(f"lin2d: {lin2d.shape}")

lin1d: (100,)
lin2d: (10, 10)


Generate a 5x5 array of random numbers called nums. Display it.

In [17]:
nums = np.random.random((5, 5))

In [18]:
print(f"array({nums})")

array([[0.10578292 0.69216266 0.74585465 0.8704437  0.25318574]
 [0.93070865 0.44867332 0.60812421 0.32904177 0.30089064]
 [0.59821805 0.66863621 0.62371899 0.49506583 0.13187326]
 [0.56308794 0.80649058 0.46855868 0.83870732 0.93240819]
 [0.22664639 0.44405262 0.49654954 0.90564242 0.66649206]])


Print out the min, max and mean of the nums array.

In [19]:
print(f"Min: {np.min(nums)}")
print(f"Max: {np.max(nums)}")
print(f"Mean: {np.mean(nums)}")

Min: 0.10578292265375977
Max: 0.932408188156123
Mean: 0.566040653445069


Multiple the entire array nums x2 and store it back in nums. Display the result.

In [20]:
nums *= 2

In [21]:
print(f"array({nums})")

array([[0.21156585 1.38432533 1.4917093  1.7408874  0.50637148]
 [1.86141729 0.89734663 1.21624843 0.65808355 0.60178127]
 [1.19643611 1.33727242 1.24743798 0.99013167 0.26374652]
 [1.12617588 1.61298115 0.93711737 1.67741464 1.86481638]
 [0.45329279 0.88810523 0.99309907 1.81128484 1.33298412]])


Select rows 1 to 2 and cols 2 to 3 and display the result.

In [22]:
selection = nums[1:3, 2:4]

In [23]:
print(f"array({selection})")

array([[1.21624843 0.65808355]
 [1.24743798 0.99013167]])


Modify that same selection by multiplying it x10, then display the new nums array.

In [24]:
selection *= 10

In [25]:
print(f"array({nums})")

array([[ 0.21156585  1.38432533  1.4917093   1.7408874   0.50637148]
 [ 1.86141729  0.89734663 12.16248429  6.58083547  0.60178127]
 [ 1.19643611  1.33727242 12.47437976  9.90131669  0.26374652]
 [ 1.12617588  1.61298115  0.93711737  1.67741464  1.86481638]
 [ 0.45329279  0.88810523  0.99309907  1.81128484  1.33298412]])


Load 'data9.npy' into a numpy array named 'data'. Display the array.

In [26]:
data = np.load('data9.npy')

In [27]:
print(f"array({data})")

array([[0.07301979 0.16473597 0.81951432 0.99818186]
 [0.62804768 0.34424393 0.58308361 0.09436134]
 [0.03345196 0.28866977 0.36343501 0.64198102]
 [0.74852967 0.08606404 0.10232671 0.86568091]
 [0.42570996 0.55892485 0.7516009  0.3855254 ]
 [0.06229575 0.95342168 0.89634407 0.43225468]
 [0.56500264 0.93069069 0.90221041 0.178963  ]
 [0.84182479 0.36880305 0.26415286 0.04403728]
 [0.78829453 0.94777048 0.14770364 0.58350887]
 [0.47231189 0.00532193 0.91274993 0.86889732]])


Find and display the *index value* of the largest number in each *row* of data. 

In [28]:
max_value = np.argmax(data, axis=1)

In [29]:
print(max_value)

[3 0 3 3 2 1 1 0 1 2]


Create a four-dimensional column vector with random numbers between 0 and 1, sampled from the uniform distribution. Name it $w$.

In [30]:
w = np.random.rand(4, 1)

In [31]:
print(w)

[[0.30611616]
 [0.10729456]
 [0.45286491]
 [0.65587782]]


Calculate the dot products between $w$ and each row of data.

In [32]:
dot_products = np.dot(data, w)

In [33]:
print(dot_products)

[[1.06584243]
 [0.55513866]
 [0.62686096]
 [0.85249231]
 [0.78351752]
 [0.81079573]
 [0.79877178]
 [0.44577537]
 [0.79260064]
 [1.12839621]]


Create a numpy array $u = (1, -1, 0)$ and a numpy array $v = (1, 0, 1)$. Calculate and display the cosine of the angle between them.

In [34]:
u = np.array([1, -1, 0])
v = np.array([1, 0, 1])

cosine_angle = np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))

In [35]:
print(cosine_angle)

0.4999999999999999
