Import numpy and pandas

In [1]:
import numpy as np
import pandas as pd

Create a python dictionary with 3 labels and 3 numbers of your choice.
Call it my_data.

In [2]:
my_data = {'year': 1999, 'month': 1, 'day': 15}
print(my_data)

{'year': 1999, 'month': 1, 'day': 15}


Create a pandas Series from the my_data dictionary, called my_series.
Display it.

In [3]:
my_series = pd.Series(my_data)
print(my_series)

year     1999
month       1
day        15
dtype: int64


Create a 5x5 array of random integers, from 0 to 100 called nums.
Display it.

In [4]:
nums = np.random.randint(0, 100, size=(5, 5))
print(f"array({nums})")

array([[66 60 87 74 51]
 [33 28 76 44  6]
 [42 71 14 59 80]
 [79 98 12 63 81]
 [73 25 87 33 63]])


Create a DataFrame from the nums array, called df.
Label the columns: A,B,C,D,E
Label the index: V,W,X,Y,Z
Display the DataFrame.

In [5]:
columns = ['A', 'B', 'C', 'D', 'E']
index = ['V', 'W', 'X', 'Y', 'Z']

data_frame = pd.DataFrame(nums, columns=columns, index=index)

print(data_frame)

    A   B   C   D   E
V  66  60  87  74  51
W  33  28  76  44   6
X  42  71  14  59  80
Y  79  98  12  63  81
Z  73  25  87  33  63


Display columns B and D.

In [6]:
print(data_frame[['B', 'D']])

    B   D
V  60  74
W  28  44
X  71  59
Y  98  63
Z  25  33


Display rows X and Y.

In [7]:
print(data_frame.loc[['X', 'Y']])

    A   B   C   D   E
X  42  71  14  59  80
Y  79  98  12  63  81


Display element YC.

In [8]:
print(data_frame.loc['Y', 'C'])

12


Display rows X and Y, and columns B and D.

In [9]:
print(data_frame.loc[['X', 'Y'], ['B', 'D']])

    B   D
X  71  59
Y  98  63


Display the rows where the number in the 'A' column is greater than 50.

In [10]:
filtered_rows = data_frame[data_frame['A'] > 50]
print(filtered_rows)

    A   B   C   D   E
V  66  60  87  74  51
Y  79  98  12  63  81
Z  73  25  87  33  63


Add a new column F, which is column A x column B.
Display the resulting DataFrame.

In [11]:
data_frame['F'] = data_frame['A'] * data_frame['B']
print(data_frame)

    A   B   C   D   E     F
V  66  60  87  74  51  3960
W  33  28  76  44   6   924
X  42  71  14  59  80  2982
Y  79  98  12  63  81  7742
Z  73  25  87  33  63  1825


Permanently drop row V and column F.
Display the resulting DataFrame.

In [12]:
data_frame.drop(['V'], inplace=True)
data_frame.drop(['F'], axis=1, inplace=True)
print(data_frame)

    A   B   C   D   E
W  33  28  76  44   6
X  42  71  14  59  80
Y  79  98  12  63  81
Z  73  25  87  33  63


Save the dataframe in a file called 'data10.csv'

In [13]:
data_frame.to_csv('data10.csv', index_label='Index')